### ISSUE TITLE
Can we use Amazon MSK as a drop in replacement for in-cluster Kafka?

### ISSUE THREAD

**Issue by steveellis** [culibraries/folio#2]
Kafka message queue is required for several modules (list at the end of this issue) and has been a challenge to manage so far. We have had at least two separate service interruptions because failed to correctly manage Kafka as we scale the number of nodes in the underlying kubernetes cluster. AWS offers a managed service [Amazon Managed Streaming for Apache Kafka](https://aws.amazon.com/msk/). 

We want to evaluate if we can use this as a drop-in replacement for Kafka deployed via a Helm chart.

## Modules that use Kafka

- mod-data-import
- mod-data-export-spring
- mod-data-export-worker
- mod-ebsconet
- mod-inventory
- mod-inventory-storage
- mod-invoice
- mod-pubsub
- mod-quick-marc
- mod-remote-storage
- mod-source-record-manager
- mod-source-record-storage

**Comment by jwfuller** [comment]
Started to provision an AWS MSK cluster. Used the custom settings so that I could pick which VPC I deployed into.

- 3 brokers, 1 per zone, each in their own networking zone (chose first 3 in list)
- Kafka v2.8.1 (2.8.0 is deployed into the Iris Sandbox cluster, the [mod-pubsub pom.xml file](https://github.com/folio-org/mod-pubsub/blob/master/mod-pubsub-server/pom.xml#L107) seems to indicate that >= v2.5.0 is required)
- Default Security Group for VPC
- `kafka.t3.small` broker size, 1 per zone
- 10 GiB storage (can only scale up)
- No autoscaling configured yet
- Allow defaults of `Unauthenticated` and `IAM` access. I think the VPC will prevent unwanted access from the outside.
- TLS encryption is enabled within the cluster and available to clients
- Data is encrypted at rest
- Basic monitoring for now
- Tagged cluster

Started creation at 10:27a

**Comment by jwfuller** [comment]
Created a Service for an external hostname in Rancher

```yml
apiVersion: v1
kind: Service
metadata:
  name: cubl-folio-msk
  namespace: kafka-iris
spec:
  externalName: [one-of-the-zookeeper-broker-hostnames]
  ports:
  - name: zookeeper-broker
    port: 2182
    protocol: TCP
    targetPort: 2182
  sessionAffinity: None
  type: ExternalName
```
